name: Build and deploy website

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v4
        with:
          environment-file: env.yml
          activate-environment: sphinx-docs
          auto-update-conda: false

      - name: Show environment information
        run: |
          python --version
          sphinx-build --version
          conda info
          conda list

      - name: Build documentation
        run: |
          sphinx-build \
            --builder html \
            --fail-on-warning \
            --keep-going \
            src \
            _build/html

      - name: Upload Pages artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v4
        with:
          path: _build/html

  deploy:
    if: github.event_name != 'pull_request'

    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
